---
title: "Advising"
---


#### My philosophy on our advising relationship
There are a few times a year that I will require my advisees to meet with me (namely: for registration), but beyond those, the type and amount of advising you would like is up to you. That being said, I am happy to meet more frequently and discuss your specific goals or concerns. You can always book an appointment with me through calendly, or email me. If none of my available times work in calendly let me know and we can find another time to meet.

::: {.column-margin}
Book an appointment to talk about anything. [calendly.com/eikmeier](https://calendly.com/eikmeier)
:::

During our meetings I often take notes – don’t worry, those are just for me to help remember what we talked about. I typically have quite a few advisees, and the small details are easily lost or jumbled in my brain.

I will sometimes have open drop-in advising hours at the beginning of the semester, feel free to stop by for quick questions or just to say hello! I enjoy hearing about what you did over the last break and what’s going on this semester.

#### My philosophy on your Grinnell education
I expect that my advisees will take a minimum of 12 credits from each division, and no, tutorial does not count towards the humanities or social sciences divisions. This happens to be one of the requirements for early graduation (actually, the requirement for early graduation is stricter: 3 4-credit courses from each division), but I believe it is also a fairly minimal expectation for someone with a liberal arts degree. Some students really struggle with this, but I encourage you to explore disciplines outside of your comfort zone. Your time in the divisions outside your major(s) will broaden your perspectives, and you may even find new academic interests.

If you are a computer science major, and you can swing it, I highly recommend taking MA-218 (as opposed to CSC-208). I will not pressure you if it’s not something you want, but if you’re on the fence MA-218 is what I recommend.

#### Registration season
Each semester when we register for classes, I will ask to meet with you individually before registration opens to discuss your plans. It is my expectation that you will come to our meeting with a general plan and courses added to colleague. At our meeting we will discuss this plan including back-up courses, and any questions about which courses you should take. I will hit “approve” once we’ve agreed so you can complete registration on the relevant day(s).

During our registration meeting I would also like to check in on how the semester is going and any concerns you have. Depending on where you are in your academic career I might bring up other topics such as study abroad, departmental honors, summer plans, etc.

#### FAQ:
Q: I want to be a computer science major! Will you be my advisor?
: A: Awesome! I would probably be delighted to be your advisor, but we assign students to advisors through a particular process. Watch your email in the spring of your second year for details on how to get an advisor, and how to state a preference for me or someone else if you’d like.

Q: You aren’t my official academic advisor, but I have a question anyway.
: A: I’m still happy to try and advise you – set up a meeting or shoot me an email. When it comes to official things like registration or signatures, you’ll need to speak to your academic advisor.

Q: What CS courses should I take next semester?
: A: Check out our department suggestions [here](https://www.grinnell.edu/about/leadership/offices-services/academic-advising/resources/registration-suggestions/computer-science).

Q: I need advice on getting internships or jobs.
: A: A much better resource than me for this is the CLS, in particular Sasha Grigorovich and Mark Peterson provide excellent advice to STEM students.

Q: Where can I see information about past courses
: A: Our department maintains a website with some links to recent course offerings. There is also a lot of really handy information about off-campus study, among other things. [cs.grinnell.edu](cs.grinnell.edu)
