---
title: "Teaching"
---
### Current
I am on sabbatical for the 2026 - 2027 school year, so I'm not teaching any classes. 

### Previous Courses

If the link is not available the content is either restricted to our LMS or otherwise unavailable.


#### 151: Functional Problem Solving
> Our first semester computer science class, taught in 
Scheme. No previous programming experience required.
[Spring 2026](https://eikmeier.sites.grinnell.edu/csc-151-spring-2026/syllabus/), 
[Fall 2025](https://eikmeier.sites.grinnell.edu/csc-151-fall-2025/syllabus/), 
[Spring 2021](https://eikmeier.sites.grinnell.edu/csc-151-s221/home/),
Spring 2020,
Fall 2019

#### 161: Imperative Problem Solving 
> Our secpmd semester computer science class, taught in 
C.

#### 208: Discrete Structures
> Traditional math for a computer science major, Calculus 1 is a prerequisite. Covers proof techniques among other things. 

#### 301: Analysis of Algorithms
> Covers advanced algorithms and data structures, and thorough understanding of runtime and space analysis. Prerequisites include Discrete structures and Data Structures (CS 207 at Grinnell)

#### 331: Algorithms, Ethics, and Society
> We attempt to understand the ramifications of technology on society, especially focused on the lens of identity.
Fall 2025, Fall 2023

#### 341: Automata, Formal Languages, and Computational Complexity
> Covers Regular Languages, Turing Machines, Complexity Theory, Undecidability, etc. 

#### Tutorial
> This is the first semester course at Grinnell College that all students are required to take. Faculty teach writing, speaking, and research fundamentals through a topic of their choice. Fall 2021
